"""Generate the pure-JVM fallback from canonical Android English resources."""
from pathlib import Path
import json,sys,xml.etree.ElementTree as ET
root=Path(__file__).resolve().parents[1]
source=root/'app/src/main/res/values/strings.xml'
rows=[]
for item in ET.parse(source).getroot().findall('string'):
    value=item.text or ''
    if value.startswith('"') and value.endswith('"'):value=value[1:-1]
    value=value.replace('\\n','\n').replace("\\'","'").replace('\\"','"')
    rows.append((item.attrib['name'],value))
body='package com.localair.airplay;\n\n// Generated by verification/generate-default-text.py. Edit values/strings.xml.\nfinal class DefaultText {\n    static String get(int id){\n'
body+=''.join(f'        if(id==R.string.{key})return {json.dumps(value,ensure_ascii=False)};\n' for key,value in rows)
body+='        throw new IllegalArgumentException("Unknown text resource: "+id);\n    }\n}\n'
target=root/'app/src/main/java/com/localair/airplay/DefaultText.java'
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8')==body,'Regenerate DefaultText.java'
else:target.write_text(body,encoding='utf-8')
print('English fallback verified:',len(rows),'strings')
